apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wltcssfz-go-gitops
  description: This is GitOps manifest for wltcssfz-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=wltcssfz-go
    backstage.io/kubernetes-id: wltcssfz-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wltcssfz-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wltcssfz-go
